
export default interface Month {
  year: number,
  month: number,
  opening_receipts: number,
  opening_primary: number,
  opening_other: number,
/*
  IS THIS NEEDED? DO WE EVEN HAVE A MONTH?
  OR DOES MONTH BECOME LIKE A DERIVED TABLE / VIEW?
  THESE REALLY FEEL LIKE DERIVED PROPERTIES ANYWAYS...

  SO MAYBE THEY USE A SUM OPERATION...

  THIS OF COURSE MEANS WE CANT DYNAMICALLY UPDATE THE OPENING BALANCE.

  IS THIS SOMETHING WE ACTUALLY NEED TO DO?

  SO THE TRANSACTION SERVICE GETS NEW METHODS
*/
}
